import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h2" gutterBottom component="div">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Typography>

        <Typography variant="p" gutterBottom component="div">
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </Typography>
      </main>
    </div>
  )
}
