import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Customer.module.css'
import Typography from '@mui/material/Typography';

export default function Customer() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Customer</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>
                <Typography variant="h2" gutterBottom component="div">
                    Customers
                </Typography>
            </main>
        </div>
    )
}
